export const SAVE_USER = "SAVE_USER"
export const FETCH_USER_FETCHING = "FETCH_TICKET_FETCHING"
export const FETCH_USER_FAIL = "FETCH_TICKET_FAIL"
export const FETCH_USER_SUCCESS = "FETCH_TICKET_SUCCESS"